import { MD3LightTheme, type MD3Theme } from "react-native-paper";

/**
 * Тема приложения: Material Design 3 + фирменный синий МойСоюз (как на вебе).
 */
export const myUnionPaperTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 14,
  colors: {
    ...MD3LightTheme.colors,
    primary: "#0A5DB5",
    onPrimary: "#FFFFFF",
    primaryContainer: "#D4E6FF",
    onPrimaryContainer: "#001E4A",
    secondary: "#5C6778",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#E1E6F0",
    onSecondaryContainer: "#1E293B",
    tertiary: "#6B4EA2",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#EDE7FF",
    onTertiaryContainer: "#1F1147",
    error: "#B3261E",
    onError: "#FFFFFF",
    errorContainer: "#F9DEDC",
    onErrorContainer: "#410E0B",
    surface: "#F8FAFC",
    onSurface: "#0F172A",
    surfaceVariant: "#E2E8F0",
    onSurfaceVariant: "#64748B",
    surfaceDisabled: "rgba(15, 23, 42, 0.12)",
    onSurfaceDisabled: "rgba(15, 23, 42, 0.38)",
    background: "#EFF3F8",
    onBackground: "#0F172A",
    outline: "#CBD5E1",
    outlineVariant: "#E2E8F0",
    shadow: "#0F172A",
    inverseSurface: "#1E293B",
    inverseOnSurface: "#F1F5F9",
    inversePrimary: "#A5C8FF",
    elevation: {
      level0: "transparent",
      level1: "#F4F7FB",
      level2: "#F1F5F9",
      level3: "#EEF2F7",
      level4: "#EBF0F6",
      level5: "#E8EDF4",
    },
  },
};
